### ISSUE TITLE
Algorithm Design in Python

### ISSUE THREAD

**Issue by jainaman224** [jainaman224/Algo_Ds_Notes#18]
We are aiming to write basic algorithms that are
- [ ] Sorting
  - [x] Bubble Sort
  - [x] Selection Sort
  - [x] Insertion Sort
  - [x] Merge Sort
  - [x] Heap Sort
  - [x] Quick Sort
  - [x] Counting Sort
  - [x] Radix Sort #43
  - [x] Shell Sort #44
  - [ ] Bucket Sort
  - [ ] Randomized Quick Sort
  - [ ] Merge Sort with Insertion Sort
- [ ] Searching
  - [x] Linear Search
  - [x] Binary Search
  - [x] Ternary Search #25
  - [x] Interpolation Search #63
- [ ] Graph
  - [ ] Depth First Search
  - [ ] Breadth First Search
  - [ ] Prims Algorithm
  - [ ] Dijkstra Algorithm
  - [ ] Floyd Warshall Algorithm
  - [ ] Topological Sort
  - [ ] Kruskal Algorithm
  - [ ] Strongly Connected Components
  - [ ] Bellman - Ford Algorithm
- [ ] Strings
  - [x] Naive Matching
  - [x] Knuth Morris Pratt #54
  - [ ] Z algorithm
  - [ ] Rabin Karp
- [ ] Dynamic Programming
  - [ ] Rod Cutting
  - [ ] Knapsack
  - [ ] Matrix Chain Multiplication
  - [ ] Longest Common subsequence
  - [x] Kadane Algorithm #49
- [ ] Greedy
  - [ ] Activity Selection
  - [ ] Huffman codes
- [ ] Number Theory
  - [ ] Modular Arithmetic
  - [x] Fermat's theorem #50 
  - [x] Sieve of Eratosthenes #45
  - [x] Logarithmic Exponentiation #52
  - [x] Euclidean method for Greatest common divisor #46
  - [x] Chinese Remainder Theorem #48 
- [ ] Game Theory
  - [ ] Nim Game
  - [ ] Grundy numbers
  - [ ] Sprague Grundy Theorem
