### ISSUE TITLE
Algorithm Design in C++

### ISSUE THREAD

**Issue by jainaman224** [jainaman224/Algo_Ds_Notes#4]
We are aiming to write basic algorithms that are
- [ ] Sorting
  - [x] Bubble Sort
  - [x] Selection Sort
  - [x] Insertion Sort
  - [x] Merge Sort
  - [x] Heap Sort
  - [x] Quick Sort
  - [x] Counting Sort (assigned to @ayushin78) #20
  - [x] Radix Sort (assigned to @sidgorey) #43 
  - [x] Shell Sort (assigned to @sidgorey) #44
  - [ ] Bucket Sort
  - [ ] Randomized Quick Sort
  - [ ] Merge Sort with Insertion Sort
  - [ ] Introsort
- [x] Searching
  - [x] Linear Search
  - [x] Binary Search
  - [x] Ternary Search #25 
  - [x] Interpolation Search #42 
- [ ] Graph
  - [x] Depth First Search (assigned to @nj4710)
  - [x] Breadth First Search
  - [x] Prims Algorithm
  - [x] Dijkstra Algorithm (assigned to @KavyaSharma)
  - [ ] Floyd Warshall Algorithm
  - [ ] Topological Sort
  - [ ] Kruskal Algorithm
  - [ ] Strongly Connected Components
  - [ ] Bellman - Ford Algorithm
- [ ] Strings
  - [x] Naive Matching (assigned to @jainaman224) #22
  - [x] Knuth Morris Pratt (assigned to @jainaman224) #28 
  - [x] Z algorithm (assigned to @jainaman224) #29 
  - [ ] Rabin Karp
- [ ] Dynamic Programming
  - [x] Fibonacci Series (assigned to @vatsrahul)
  - [x] Rod Cutting (assigned to @KavyaSharma)
  - [x] Knapsack
  - [x] Matrix Chain Multiplication
  - [ ] Longest Common subsequence
  - [x] Kadane Algorithm (assigned to @ayushin78) #35 
- [ ] Greedy
  - [ ] Activity Selection
  - [ ] Huffman codes
- [ ] Number Theory
  - [ ] Modular Arithmetic
  - [ ] Fermat's theorem (assigned to @KavyaSharma)
  - [x] Sieve of Eratosthenes
  - [ ] Logarithmic Exponentiation (assigned to @KavyaSharma)
  - [x] Euclidean method for Greatest common divisor
  - [ ] Extended Euclidean Algorithm  (assigned to @KavyaSharma)
  - [x] Chinese Remainder Theorem (assigned to @KavyaSharma)
- [ ] Game Theory
  - [ ] Nim Game
  - [ ] Grundy numbers
  - [ ] Sprague Grundy Theorem
