### ISSUE TITLE
Data Structures in C++

### ISSUE THREAD

**Issue by jainaman224** [jainaman224/Algo_Ds_Notes#5]
We are aiming to write basic Data structures
- [x] Arrays
- [ ] Lists
  - [ ] Linked Lists
    - [x] Singly Linked List
    - [ ] Doubly Linked List (assigned to @vatsrahul)
    - [x] Circular Linked List (assigned to @vatsrahul)
  - [x] Stacks
    - [x] Using Arrays
    - [x] Using Linked List
  - [ ] Queues
    - [x] Using Arrays
    - [x] Using Linked List (assigned to @sidgorey) #23 
    - [ ] Priority Queues
      - [ ] Using Linked List
      - [ ] Using Heap
- [ ] Trees
  - [ ] Binary Tree
  - [x] Binary Search Tree
  - [ ] Heaps
  - [x] Trie
    - [x] English words (assigned to @jainaman224) #19 
    - [x] Natural numbers (assigned to @jainaman224) #19 
  - [ ] B Trees
  - [ ] Red Black Trees
  - [x] Binomial Heap
  - [ ] Fibonacci Heap
  - [ ] Segmented Tree
  - [ ] Fenwick Tree / Binary Indexed Tree
  - [ ] Suffix Tree
  - [ ] AVL Trees
  - [ ] Multi Way Trees
- [ ] Hash Tables and Hash Functions
